### PR TITLE
Fix: Cat facts API no longer available

### PR DESCRIPTION
**Pull request by thinkverse**
Hello there. 👋

## Related issues.

I had this issue before and notified staff on the forums about this issue. Saw the issue (#9) was still open and had been marked for Hacktoberfest. So here's the solution I came up with to fixed the issue.

## Suggested solution.

I changed the API to the [catfact.ninja] and updated the wording on the response to match it. The `main.py` has been modified for the new API and returns a similar result set from the old API, just with a different key, `text` to `fact`.
But since the `::set-output` doesn't change and just returns a string, the other responses don't have to change as well.

## Any tests?

No, I tried to create a new course based on the fork but it won't let me. It just keeps loading so I'm now 100% on how to actually test this. 😕

[catfact.ninja]:https://catfact.ninja/

### CODE REVIEW

**Comment by thinkverse** [comment]
Also, will the `hacktoberfest` topic be added to this repository? Since Hacktoberfest is not [opt-in as per this tweet]. 🤔

[opt-in as per this tweet]: https://twitter.com/hacktoberfest/status/1312221208667185153

**Comment by Jleeblanch** [comment]
I got to this step last evening, and discovered the current cat-facts api is down again. Being the code for it is also on GitHub, it seems this isn't the first time that api has been down. 

Reference: https://github.com/alexwohlbruck/cat-facts/issues

Long story short, I found another cat fact api, the same one used in the changes in this PR, and by updating the Python code to what is seen in this PR, I was able to output a random cat fact as expected and am finally able to continue with the course 😅

**Comment by jung-youjin** [comment]
Just tried out cat-facts api as well and it was down for me too 😥 But this works like a charm! Thank you! 😁

**Comment by thinkverse** [comment]
Glad this PR was helpful to you all. 🙂 Seems the issue of the outdated API is persisting, pinging in @hectorsector and @brianamarie to see if there's have any intention of merging this PR so the issue can perhaps be resolved. 🤷‍♂️

**Comment by brianamarie** [comment]
Thank you for this contribution, @thinkverse! 

@mattdavis0351, would you have bandwidth to review this?

Or, @thinkverse, maybe you and I could coordinate something - Maybe we could figure out a day/time to merge this, if you're available to test and confirm that it works as intended, and I could be on call to revert if something unexpected happens. (It's a bit riskier but probably the fastest.) 

What do you think @thinkverse?

**Comment by thinkverse** [comment]
Actually @brianamarie, this PR might not be needed anymore. 🤔 Just ran the code in main and it seems that the original cat-fact API is back up and running again, making this PR obsolete. 🤷‍♂️

**Comment by brianamarie** [comment]
That's great news, @thinkverse! I'm going to close this PR for now, but in the event we need it, we can always reopen. 😊

**Pull request closed without merging**
